config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :urls do
  	collection do
      get :stats
    end
  end

  root :to => "urls#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/get_short_url.rb
module GetShortUrl
  extend ActiveSupport::Concern


  module ClassMethods
    def generate_short_url
      short_url = 'short.com'    #the static part of the shorturl which is pointed to our application
      chars = ['0'..'9', 'A'..'Z', 'a'..'z'].map { |range| range.to_a }.flatten #creates map of 62 chars
      short_url = short_url + '/' + 5.times.map { chars.sample }.join #choose 6 characters randomly and join them which have 62^6 possibilities
      return short_url
    end

    def sanitize_url(long_url)
      original_url = long_url.strip
      sanitized_url = original_url.downcase.gsub(/(https?:\/\/)|(www\.)/, '') #removing the http:, https: and www part from url
      sanitized_url.slice!(-1) if sanitized_url[-1] == '/'
      return "http://#{sanitized_url}"
    end
  end
end

app/models/short_url.rb
class ShortUrl < ApplicationRecord
  include GetShortUrl

  #takes the long url as parameter and calls concern methods to first sanitize and then check if the url exists or not
  #if the url exists it lookup for the short url in db
  #if it does not exists it creates new entry in db
  def self.create_short_link(long_url)
    sanitized_url = sanitize_url(long_url)
    duplicate_url = self.find_by_long_url(sanitized_url)
    if duplicate_url.present?
      number_of_hits = duplicate_url.number_of_hits.to_i
      duplicate_url.number_of_hits = number_of_hits + 1
      duplicate_url.save
      return duplicate_url
    else
      short_url = generate_short_url
      short_url_object = self.new({
                                   :long_url => sanitized_url,
                                   :short_url => short_url,
                                   :number_of_hits => 1
                                  })
      short_url_object.save
      return short_url_object
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  respond_to :json, :js, :html
  skip_before_action :verify_authenticity_token

  require 'uri'

  def index
  end

  def create
    ShortUrl.create_short_link(params["url"]["long_url"])
  end

  def stats
    @all_urls = ShortUrl.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/_list.html.erb
<br><br>
<br><br>
<br><br>
<br><br>
<div class="container">
	<h3>Trending URL's</h3>
	<table class="table table-bordered table-striped">
		<tr>
			<th>#</th>
			<th>Short URL</th>
			<th>Original URL</th>
		</tr>
		<% all_urls.order(number_of_hits: :desc).each_with_index do |url, index|%>
			<tr>
				<td><%= index + 1 %></td>
				<td><%= link_to "#{url.short_url}", url.long_url, target: "_blank" %></td>
				<td><%= url.long_url %></td>
			</tr>
		<% end %>
	</table>
</div>

app/views/urls/create.js.erb
$("#default_url_list").remove();
$('#ajax_url_list').html("<%= j (render 'urls/list', all_urls: ShortUrl.all) %>");

app/views/urls/index.html.erb
<div id="wrapper">
  <div id="page-wrapper" class="gray-bg">
    <div class="wrapper wrapper-content">
      <div class="row list-row">
        <div class="col-md-12">
          <h3 class="page-heading text-center">
            Welcome to short.com
          </h3>
        </div>
        <br><br>
        <br><br>
        <div class="container">
          <div class="col-md-6">
            <b> Please enter your URL here</b>
            <%= form_for :url, remote: true do |f|   %>
              <div class="form-group">
                <%= f.text_field  :long_url, class: "form-control" %>
                <%= f.submit "Shorten", class: "btn btn-primary short_button" %>
            <% end %>
            <br>
            <br>
            <div>
              <%= link_to "Stats", stats_urls_path, class: "btn btn-primary" %>
            </div>
          </div>
        </div>
        <div id="default_url_list"><%= render 'urls/list', all_urls: ShortUrl.all %></div>
        <div id="ajax_url_list"></div>
      </div>
    </div>
  </div>
</div>

app/views/urls/stats.html.erb
<div class="col-md-12" >
  <b>Analytics</b>
</div>
<br>
<br>
<div class="col-md-12" >
  <%  @all_urls.each_with_index { |url |    %>
    <b><%= url.long_url %></b><br>
    <%= url.short_url %><br>
    Total Clicks: <%= url.number_of_hits %><br>
    Top Countries:
    <hr>
  <%
    }
  %>
</div>